[auth]
 redirect_uri = "${STREAMLIT_REDIRECT_URI}"
 cookie_secret = "${STREAMLIT_COOKIE_SECRET}"
 client_id = "${STREAMLIT_CLIENT_ID}"
 client_secret = "${STREAMLIT_CLIENT_SECRET}"
 server_metadata_url = "${STREAMLIT_SERVER_METADATA_URL}"
